version: '3'

services: 
    web:
        build: .
        ports:
            - "8085:5000"
        volumes:
            - .:/code
        environment:
            FLASK_DEBUG: 1
    redis:
        image: "redis:alpine"